In [ ]:
import pandas as pd
df=pd.read_csv("FILES/Flavors.csv")
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

Groupu by Method

In [15]:
df.groupby('Base Flavor')

Use some variable

In [18]:
grouped_by_frame =df.groupby('Base Flavor')
grouped_by_frame

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000020D58536EA0>

The above error indicating that indicates that df.groupby('Base Flavor') returns a GroupBy object, not the actual grouped data.

After grouping, We need to apply an aggregation function like .mean(), .sum(), .count(), etc., to see the results.

In [19]:
grouped_by_frame.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [20]:
grouped_by_frame.mean(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [23]:
df.groupby('Base Flavor').mean(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [24]:
df.groupby('Base Flavor').count()

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         3      3              3               3             3
Vanilla           6      6              6               6             6

In [25]:
df.groupby('Base Flavor').min()

                  Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate      Chocolate   Yes            8.2             7.0          15.2
Vanilla      Cake Batter    No            2.3             3.4           5.7

In [26]:
df.groupby('Base Flavor').max()

                 Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate    Rocky Road   Yes            8.8             7.6          16.6
Vanilla         Vanilla   Yes           10.0             8.0          18.0

In [29]:
df.groupby('Base Flavor').sum()

,Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
Base Flavor,,,,,
Chocolate,ChocolateRocky RoadChocolte Fudge Brownie,YesYesYes,25.2,21.7,47.1
Vanilla,Mint Chocolate ChipVanillaCookie DoughPistachi...,YesNoYesNoYesNo,34.2,33.9,68.1

In [30]:
df.groupby('Base Flavor').sum(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate             25.2            21.7          47.1
Vanilla               34.2            33.9          68.1

Aggregation using agg function

Here we need to pass as a dictionary

{'<Column_name>':'<Aggregate_Function>'}

Can also be the list

{'<Column_name>':'[<Aggregate_Function>,<Aggregate_Function>,<Aggregate_Function>]'}

In [31]:
df.groupby('Base Flavor').agg({'Flavor Rating':'max'})

             Flavor Rating
Base Flavor
Chocolate              8.8
Vanilla               10.0

In [33]:
df.groupby('Base Flavor').agg({'Flavor Rating':['max','min','sum','mean','count']})

            Flavor Rating
                      max  min   sum mean count
Base Flavor
Chocolate             8.8  8.2  25.2  8.4     3
Vanilla              10.0  2.3  34.2  5.7     6

In [35]:
df.groupby('Base Flavor').agg({'Flavor Rating':['max','min','sum','mean','count'],
                               'Texture Rating':['max','min','sum','mean','count']})

            Flavor Rating                       Texture Rating             \
                      max  min   sum mean count            max  min   sum
Base Flavor
Chocolate             8.8  8.2  25.2  8.4     3            7.6  7.0  21.7
Vanilla              10.0  2.3  34.2  5.7     6            8.0  3.4  33.9


                 mean count
Base Flavor
Chocolate    7.233333     3
Vanilla      5.650000     6

Till now we grouped one column we can also group multiple columns

In [36]:
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [40]:
df.groupby(['Base Flavor','Liked']).min(numeric_only=True)

                   Flavor Rating  Texture Rating  Total Rating
Base Flavor Liked
Chocolate   Yes              8.2             7.0          15.2
Vanilla     No               2.3             3.4           5.7
            Yes              6.5             6.0          12.5

In [41]:
df.groupby(['Base Flavor','Liked']).agg({'Flavor Rating':['max','min','sum','mean','count'],
                               'Texture Rating':['max','min','sum','mean','count']})

                  Flavor Rating                       Texture Rating       \
                            max  min   sum mean count            max  min
Base Flavor Liked
Chocolate   Yes             8.8  8.2  25.2  8.4     3            7.6  7.0
Vanilla     No              4.7  2.3  10.8  3.6     3            5.0  3.4
            Yes            10.0  6.5  23.4  7.8     3            8.0  6.0


                    sum      mean count
Base Flavor Liked
Chocolate   Yes    21.7  7.233333     3
Vanilla     No     13.4  4.466667     3
            Yes    20.5  6.833333     3

We can use Describe function to get overall view

In [42]:
df.groupby(['Base Flavor','Liked']).describe()

                  Flavor Rating                                             \
                          count mean       std  min   25%  50%   75%   max
Base Flavor Liked
Chocolate   Yes             3.0  8.4  0.346410  8.2  8.20  8.2  8.50   8.8
Vanilla     No              3.0  3.6  1.212436  2.3  3.05  3.8  4.25   4.7
            Yes             3.0  7.8  1.915724  6.5  6.70  6.9  8.45  10.0

                  Texture Rating            ...            Total Rating  \
                           count      mean  ...   75%  max        count
Base Flavor Liked                           ...
Chocolate   Yes              3.0  7.233333  ...  7.35  7.6          3.0
Vanilla     No               3.0  4.466667  ...  5.00  5.0          3.0
            Yes              3.0  6.833333  ...  7.25  8.0          3.0


                        mean       std   min    25%   50%    75%   max
Base Flavor Liked
Chocolate   Yes    15.700000  0.781025  15.2  15.25  15.3  15.95  16.6
Vanilla     No      8.066667  2.098412   5.7   7.25   8.8   9.25   9.7
            Yes    14.633333  2.950141  12.5  12.95  13.4  15.70  18.0

[3 rows x 24 columns]